# Generated by Django 2.2.4 on 2021-05-26 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg_app', '0006_auto_20210526_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bdate',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 22, 24, 6, 125957)),
        ),
    ]
