# Generated by Django 2.2.4 on 2021-05-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiTv_app', '0002_auto_20210525_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
