# Generated by Django 2.2.4 on 2021-05-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiTv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='releaseDate',
            field=models.DateField(verbose_name='%b %d, %Y'),
        ),
    ]
