# Generated by Django 2.2.4 on 2021-05-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
