# Generated by Django 2.2.4 on 2021-05-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg_app', '0003_remove_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdaydate',
            field=models.DateField(default='2021-05-05'),
            preserve_default=False,
        ),
    ]
