# Generated by Django 2.2.4 on 2021-05-26 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg_app', '0007_auto_20210526_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('Bdate', models.DateField(default=datetime.datetime(2021, 5, 26, 22, 39, 14, 719650))),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Bdate',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 22, 39, 14, 613493)),
        ),
    ]
