# Generated by Django 2.2.4 on 2021-05-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjaTemplate_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojos',
            name='desc',
        ),
    ]
