# Generated by Django 2.2.4 on 2021-05-26 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg_app', '0008_auto_20210526_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bdate',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 22, 42, 45, 267484)),
        ),
        migrations.AlterField(
            model_name='userr',
            name='Bdate',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 22, 42, 45, 361233)),
        ),
    ]
