# Generated by Django 2.2.4 on 2021-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthors_app', '0002_remove_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
    ]
