# Generated by Django 2.2.4 on 2021-05-26 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg_app', '0005_user_bdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdaydate',
        ),
        migrations.AlterField(
            model_name='user',
            name='Bdate',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 22, 16, 51, 535818)),
        ),
    ]
